import product1 from "../../assets/products/product1.png";
import product2 from "../../assets/products/product2.png";
import product3 from "../../assets/products/product3.jpg";
import product4 from "../../assets/products/product4.jpg";
import product5 from "../../assets/products/product5.jpg";

const products = [
  {
    id: 1,
    image: product1,
    badge: "Today's Deal",
    inStock: true,
    title: "Bicillin Tablets 30 mg",
    manufacturer: "Bayer",
    dosage: "30 Tablets",
    code: "152349",
    rating: 4,
    price: "41.108",
    oldPrice: "49.999",
    buttonText: "Buy in 1 Click",
    available: true,
  },
  {
    id: 2,
    image: product2,
    badge: "Today's Deal",
    inStock: true,
    title: "Femibion Vitamin Tablets",
    manufacturer: "Bayer",
    dosage: "30 Tablets",
    code: "152349",
    rating: 5,
    price: "41.108",
    oldPrice: "49.999",
    buttonText: "Buy in 1 Click",
    available: true,
  },
  {
    id: 3,
    image: product3,
    badge: "Today's Deal",
    inStock: true,
    title: "Bifiform Capsules",
    manufacturer: "Bayer",
    dosage: "30 Tablets",
    code: "152349",
    rating: 4,
    price: "41.108",
    oldPrice: "49.999",
    buttonText: "Buy in 1 Click",
    available: true,
  },
  {
    id: 4,
    image: product4,
    badge: "Today's Deal",
    inStock: true,
    title: "Detragel Gel",
    manufacturer: "Bayer",
    dosage: "30 Tablets",
    code: "152349",
    rating: 5,
    price: "41.108",
    oldPrice: "49.999",
    buttonText: "Buy in 1 Click",
    available: true,
  },
  {
    id: 5,
    image: product5,
    badge: "Today's Deal",
    inStock: false,
    title: "Heptral Tablets",
    manufacturer: "Bayer",
    dosage: "30 Tablets",
    code: "152349",
    rating: 4,
    price: "41.108",
    oldPrice: "49.999",
    buttonText: "Notify Me",
    available: false,
  },
];

export default products;